[package]
name = "multisplice"
version = "0.1.0"
description = "easily splice a string multiple times, using offsets into the original string"
authors = ["Ren√©e Kooi <renee@kooi.me>"]

[dependencies]
